const fs=require('fs'),assert=require('node:assert/strict');const {serve}=require('./shot.cjs');
async function decodedImages(page){for(const img of await page.locator('article img').all()){await img.scrollIntoViewIfNeeded();await img.evaluate(async el=>{await el.decode();if(!el.naturalWidth||!el.naturalHeight)throw Error('Missing rendered evidence');});}}
(async()=>{const out=process.argv[2]||'test-results/full-rollout/gallery';fs.mkdirSync(out,{recursive:true});const server=await serve(),browser=await require('playwright').chromium.launch({args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});const page=await browser.newPage({viewport:{width:390,height:844}}),errors=[];page.on('pageerror',e=>errors.push(String(e)));const base='http://127.0.0.1:'+server.address().port;
try{await page.goto(base+'/character-3d/full-gallery.html');await page.locator('article').first().waitFor();assert.equal(await page.locator('article').count(),8);assert.ok(await page.locator('img').count()<=40);await page.locator('#search').fill('cat');await page.locator('#kind').selectOption('form');assert.equal(await page.locator('article').count(),8);await page.locator('#stage').selectOption('4');assert.equal(await page.locator('article').count(),1);assert.match(await page.locator('article h2').innerText(),/cat 04/);assert.equal(await page.locator('article img').count(),5);await decodedImages(page);const firstImage=page.locator('article img').first(),savedSrc=await firstImage.getAttribute('src');await assert.rejects(firstImage.evaluate(async el=>{el.src='/__qa_missing_image__.png';await el.decode();}));await firstImage.evaluate((el,src)=>{el.src=src;},savedSrc);await decodedImages(page);await page.screenshot({path:out+'/gallery-mobile.png',fullPage:true});await page.goto(base+'/character-3d/gallery.html?id=cat&stage=4');await page.waitForFunction(()=>window.__c3d?.items.length===1);const actual=await page.evaluate(()=>{const i=window.__c3d.items[0];return {stage:i.inst.tpl.stage,pose:i.inst.meta.idlePose};});assert.deepEqual(actual,{stage:4,pose:'stretchPlay'});
await page.goto(base+'/character-3d/full-gallery.html');await page.locator('article').first().waitFor();
const rows=await page.evaluate(async()=>{const d=await fetch('../docs/qa/character-3d-full-v0/coverage.json').then(r=>r.json());return d.rows.filter(r=>r.kind!=='form'&&r.exact).map(r=>({kind:r.kind,id:r.id}));});
const live=await browser.newPage({viewport:{width:390,height:844}});live.on('pageerror',e=>errors.push(String(e)));const nonplayers=[];
for(const row of rows){await page.locator('#search').fill(row.id);await page.locator('#kind').selectOption(row.kind);assert.equal(await page.locator('article').count(),1,row.kind+':'+row.id);assert.equal(await page.locator('article img').count(),5,row.kind+':'+row.id+' complete evidence');await decodedImages(page);const href=await page.locator('article a').getAttribute('href');const expected=require('../../character-3d/spec.js').specKeyFor(row);assert.equal(new URL(href,base).searchParams.get('id'),expected.id);await live.goto(base+'/character-3d/'+href.replace('layout=views','layout=single'));await live.waitForFunction(()=>window.__c3d?.items.length===1);const result=await live.evaluate(()=>{const i=window.__c3d.items[0];return {id:i.id,stage:i.inst.tpl.stage,status:i.inst.tpl.status};});assert.deepEqual(result,{id:expected.id,stage:0,status:'ok'});nonplayers.push({...row,...result});}
await live.close();assert.equal(rows.length,Object.keys(require('../../character-3d/spec.js').NON_PLAYER).length+Object.keys(require('../../character-3d/spec.js').ARCHETYPE_REUSE).length);assert.deepEqual(errors,[]);fs.writeFileSync(out+'/result.json',JSON.stringify({source:process.env.GITHUB_SHA,pass:true,missingImageControl:'rejected',decodedEvidence:true,nonplayers,viewport:'390x844 Chromium / SwiftShader; not iPhone',errors},null,2));}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
