// Role-exact candidates: four views, all32states and actual Meguru party distance.
const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),sharp=require('sharp');
const factory=require('../../character-3d/nonplayer-spec.js'),SPEC=require('../../character-3d/spec.js'),{serve}=require('./shot.cjs');
function captureRows(keys=[]){const all=factory();for(const key of keys)assert.ok(Object.hasOwn(all,key),'unknown capture key: '+key);return Object.entries(all).filter(([key])=>!keys.length||keys.includes(key)).map(([key,row])=>{assert.equal(key,row.kind+':'+row.id);assert.ok(fs.existsSync(path.resolve(__dirname,'../..',row.asset)));return {key,...row};});}
function saveFor(row){const {harness}=require('../../tests/helpers/runtime-harness.cjs'),h=harness({deterministic:true,fullDisplay:true}),s=h.api.state(),life=require('../../life-stage-profiles.js');Object.assign(s,{stage:'growing',speciesLine:'dog',stageIndex:3,ageTicks:(life.minsForLine('dog')[3]+.5)*20,isSleeping:false,isSick:false,energy:100,health:100,hunger:85,happiness:90,regionId:'forest',companions:[],partner:null,discoveredStages:[]});s.lifetime.companionsRecruited=[];s.lifetime.rareCompanionsRecruited=[];s.lifetime.partnersRecorded=[];if(row.kind==='companion'){s.companions=[{id:row.id,bond:100}];s.lifetime.companionsRecruited=[row.id];}else if(row.kind==='partner'){s.partner={id:row.id,bond:100};s.lifetime.partnersRecorded=[row.id];}else throw Error('Author distance route not yet implemented');return JSON.stringify(s);}
function installDistancePose(sim,actor,view){
 const original=sim.step,heading=view==='front'?Math.PI:0;
 function hold(){actor.x=sim.player.x+85;actor.z=sim.player.z+15;actor.tx=actor.x;actor.tz=actor.z;actor.heading=heading;actor.route=null;actor.behavior='idle';actor.until=1e9;}
 sim.step=function(...args){const events=original.apply(this,args);hold();return events;};hold();
 return ()=>{sim.step=original;};
}
async function run(out){fs.mkdirSync(out,{recursive:true});const filter=process.argv.find(a=>a.startsWith('--keys='))?.slice(7).split(',')||[],rows=captureRows(filter),srv=await serve({nonPlayerFactory:factory}),base='http://127.0.0.1:'+srv.address().port,browser=await require('playwright').chromium.launch({args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']}),errors=[],evidence=[],distance=[];const watch=p=>{p.on('pageerror',e=>errors.push(String(e)));};try{
 const page=await browser.newPage({viewport:{width:320,height:320},deviceScaleFactor:1});watch(page);
 for(const row of rows){const prefix=row.kind+'-'+row.id,original=await sharp(path.resolve(__dirname,'../..',row.asset)).trim().resize(280,280,{fit:'contain',background:'#eee9dd'}).extend({top:20,bottom:20,left:20,right:20,background:'#eee9dd'}).png().toBuffer(),views=[{input:original,left:0,top:0}],states=[];
 async function shot(view,emotion,moving,reduced,file){const query=new URLSearchParams({id:row.key,stage:'0',view,emotion,walk:moving?'1':'0',reduced:reduced?'1':'0'});await page.goto(base+'/character-3d/wave-review.html?'+query);await page.waitForFunction(()=>window.__wave?.ready);const r=await page.evaluate(()=>window.__wave);assert.equal(r.id,row.key);assert.equal(r.stage,0);assert.equal(r.emotion,emotion);assert.equal(r.moving,moving);assert.equal(r.reduced,reduced);assert.ok(r.triangles>0);await page.screenshot({path:path.join(out,file),type:'jpeg',quality:88});evidence.push({...r,kind:row.kind,masterId:row.id,file});}
 for(const[i,v]of ['front','34','side','back'].entries()){const file=prefix+'-0-'+v+'.jpg';await shot(v,'normal',false,false,file);views.push({input:path.join(out,file),left:(i+1)*320,top:0});}
 await sharp({create:{width:1600,height:320,channels:3,background:'#eee9dd'}}).composite(views).jpeg({quality:90}).toFile(path.join(out,prefix+'-views.jpg'));
 for(const[y,em]of SPEC.CANONICAL_EMOTIONS.entries()){states.push({input:original,left:0,top:y*320});for(const[x,p]of [{moving:false,reduced:false},{moving:true,reduced:false},{moving:false,reduced:true},{moving:true,reduced:true}].entries()){const file=prefix+'-0-'+em+'-'+(p.moving?'walk':'idle')+'-'+(p.reduced?'reduced':'normal')+'.jpg';await shot('34',em,p.moving,p.reduced,file);states.push({input:path.join(out,file),left:(x+1)*320,top:y*320});}}
 await sharp({create:{width:1600,height:2560,channels:3,background:'#eee9dd'}}).composite(states).jpeg({quality:90}).toFile(path.join(out,prefix+'-motion.jpg'));
 const ctx=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:2}),pg=await ctx.newPage();watch(pg);await pg.addInitScript({content:'globalThis.__installDistancePose='+installDistancePose.toString()+';'});await pg.addInitScript(s=>localStorage.setItem('naotocchi-save-v1',s),saveFor(row));await pg.goto(base+'/index.html?meguru3d=1&char3d=1&perf=1');await pg.locator('.device.ui-home-active').waitFor({timeout:60000});await pg.locator('#travelBtn').click();await pg.locator('#meguruEnterBtn').waitFor({state:'visible'});await pg.locator('#meguruEnterBtn').click();await pg.locator('#mgrCanvas').waitFor({state:'visible'});await pg.waitForFunction(({kind,id})=>{const r=globalThis.__meguruRun,a=r?.party.find(a=>a.kind===kind&&a.id===id);return a&&r.renderer.char3dPresenter?.has(a);},{kind:row.kind,id:row.id},{timeout:60000});
 for(const view of ['front','back']){const r=await pg.evaluate(async({kind,id,key,view})=>{const r=globalThis.__meguruRun,s=r.sim,a=r.party.find(a=>a.kind===kind&&a.id===id);s.setCameraMotion(false);const spot=r.world.spots.find(x=>x.id==='entry');s.setPlayer(spot.x,spot.z-100);s.camera.yaw=0;if(globalThis.__npRelease)globalThis.__npRelease();globalThis.__npRelease=globalThis.__installDistancePose(s,a,view);if(!s.__npEnv){s.__npEnv=true;const setEnv=s.setEnv.bind(s);s.setEnv=e=>setEnv({...e,time:'day',weather:'sunny'});}s.setEnv(s.env);for(let i=0;i<45;i++)await new Promise(requestAnimationFrame);const SPEC=(await import('/character-3d/spec-esm.mjs')).default;const inst=r.renderer.char3dPresenter.instanceOf(a),target=view==='front'?0:Math.PI,yawError=Math.abs(Math.atan2(Math.sin(inst.holder.rotation.y-target),Math.cos(inst.holder.rotation.y-target)));return {kind,id,key,view,actorHeading:a.heading,renderedYaw:inst.holder.rotation.y,yawError,specKey:SPEC.specKeyFor({kind,id}),live3d:r.renderer.char3dPresenter.has(a),stats:r.renderer.char3dPresenter.stats()};},{kind:row.kind,id:row.id,key:row.key,view});assert.ok(r.yawError<.02,'actual rendered heading must match requested '+view);assert.equal(r.specKey.id,row.key);assert.equal(r.specKey.stage,0);assert.equal(r.specKey.exact,true);assert.ok(r.live3d);assert.equal(r.stats.fallbacks,0);assert.equal(r.stats.failedTemplates,0);const clip=await pg.locator('#mgrCanvas').boundingBox(),file=prefix+'-distance-'+view+'.jpg';await pg.screenshot({path:path.join(out,file),clip,type:'jpeg',quality:92});distance.push({...r,file});}await ctx.close();
 }
 assert.deepEqual(errors,[]);assert.equal(evidence.length,rows.length*36);assert.equal(distance.length,rows.length*2);fs.writeFileSync(path.join(out,'evidence.json'),JSON.stringify({sourceCommit:process.env.GITHUB_SHA||null,platform:'Chromium/SwiftShader; not iPhone',candidateOnly:true,evidence,distance,errors},null,2));
 }finally{await browser.close();srv.close();}}
module.exports={captureRows,saveFor,installDistancePose};if(require.main===module)run(process.argv[2]||'test-results/full-rollout/nonplayer').catch(e=>{console.error(e);process.exitCode=1;});
