// Role-exact QA: candidate views/states/distance, optional reviewed legacy view reuse.
const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),sharp=require('sharp');
const factory=require('../../character-3d/nonplayer-spec.js'),SPEC=require('../../character-3d/spec.js'),{serve}=require('./shot.cjs');
function captureRows(keys=[],{includeLegacyStatesDistance=false}={}){
 const all=factory();for(const key of keys)assert.ok(Object.hasOwn(all,key),'unknown capture key: '+key);
 const rows=Object.entries(all).filter(([key])=>!keys.length||keys.includes(key)).map(([key,row])=>{assert.equal(key,row.kind+':'+row.id);assert.ok(fs.existsSync(path.resolve(__dirname,'../..',row.asset)));return {key,modelKey:key,...row};});
 if(includeLegacyStatesDistance){const review=require('../../docs/qa/character-3d-full-v0/legacy-four-view-review.json');for(const id of ['cat_friend','shiba']){const key='companion:'+id,k=SPEC.specKeyFor({kind:'companion',id}),reuse=review.rows.find(r=>r.key===key);assert.equal(k.id,id);assert.ok(reuse?.actualReview==='PASS_FOUR_VIEWS_ONLY','reviewed legacy four views');rows.push({key,modelKey:id,kind:'companion',id,asset:SPEC.referenceAsset(id,0),spec:SPEC.stageSpec(id,0),reuseFourViews:true,reuse:{...reuse,sourceCommit:review.sourceCommit,currentComparisonCommit:review.currentComparisonCommit,sourceMetadata:review.sourceMetadata}});}}
 return rows;
}
function capturePlan(row){return {roleKey:row.key,modelKey:row.modelKey||row.key,fourViews:row.reuseFourViews?[]:['front','34','side','back'],states:SPEC.CANONICAL_EMOTIONS.flatMap(emotion=>[{moving:false,reduced:false},{moving:true,reduced:false},{moving:false,reduced:true},{moving:true,reduced:true}].map(p=>({emotion,...p}))),distanceViews:['front','back'],reuseFourViews:!!row.reuseFourViews,reuse:row.reuse||null};}
function saveFor(row){const {harness}=require('../../tests/helpers/runtime-harness.cjs'),h=harness({deterministic:true,fullDisplay:true}),s=h.api.state(),life=require('../../life-stage-profiles.js');Object.assign(s,{stage:'growing',speciesLine:'dog',stageIndex:3,ageTicks:(life.minsForLine('dog')[3]+.5)*20,isSleeping:false,isSick:false,energy:100,health:100,hunger:85,happiness:90,regionId:'forest',companions:[],partner:null,discoveredStages:[]});s.lifetime.companionsRecruited=[];s.lifetime.rareCompanionsRecruited=[];s.lifetime.partnersRecorded=[];if(row.kind==='companion'){s.companions=[{id:row.id,bond:100}];s.lifetime.companionsRecruited=[row.id];}else if(row.kind==='partner'){s.partner={id:row.id,bond:100};s.lifetime.partnersRecorded=[row.id];}else if(row.kind==='author'&&row.id==='naoto'){s.lifetime.dexCleared=true;s.regionId='memory_lake';}else throw Error('Unknown distance identity');return JSON.stringify(s);}
function stageAuthorResident(run,bridge,M){
 if(!bridge.isAuthorUnlocked())throw Error('Author QA requires existing legal unlock');
 const sourceWorld=run.world,actor=sourceWorld.residents.find(a=>a.kind==='naoto'&&a.id==='naoto'&&a.key==='naoto');
 if(sourceWorld.regionId!=='memory_lake'||!actor||actor.asset!=='assets/characters/author/naoto.png')throw Error('Actual memory_lake author resident required');
 if(run.party.includes(actor)||run.renderer.is3D!==false)throw Error('Natural author must remain a 2D resident');
 if(!M.WORLD3D_REGIONS.has('forest')||M.WORLD3D_REGIONS.has('memory_lake'))throw Error('Unchanged production 3D region policy required');
 const sim=M.createSimulation({regionId:'forest',registry:M.buildRegistry(),world3d:true}),target=sim.world;
 const identity={key:actor.key,kind:actor.kind,id:actor.id,asset:actor.asset},index=sourceWorld.residents.indexOf(actor),draw=run.renderer.draw,step=run.sim.step,rest={};for(const k of ['x','z','tx','tz','heading','route','behavior','until'])rest[k]=actor[k];
 // Place the same resident inside the renderer's near3D range before waiting for presenter readiness.
 Object.assign(actor,{x:sim.player.x+85,z:sim.player.z+15,tx:sim.player.x+85,tz:sim.player.z+15,heading:Math.PI,route:null,behavior:'idle',until:1e9});
 sourceWorld.residents.splice(index,1);target.residents.push(actor);
 run.sim.step=function(...args){const events=step.apply(this,args);sim.step(...args);return events;};
 run.renderer.draw=function(_view,now){return draw.call(this,sim.view(),now);};
 const provenance={originalRegion:'memory_lake',originalSpot:actor.spot?.id||actor.spot||'deep',originalCoordinates:{x:rest.x,z:rest.z,heading:rest.heading},naturalPresentation:'2D',qaPlacementRegion:'forest',qaPlacement:'same actual resident object in existing forest simulation resident list; bounded renderer.draw view adapter',actor:identity,sameActorObject:target.residents.includes(actor),party:false,saveObjectChanged:false,bridgeGetterChanged:false};
 let released=false;return {actor,sim,provenance,release(){if(released)return;released=true;run.renderer.draw=draw;run.sim.step=step;const i=target.residents.indexOf(actor);if(i>=0)target.residents.splice(i,1);sourceWorld.residents.splice(index,0,actor);Object.assign(actor,rest);}};
}
function distanceActor(run,row,stage){return row.kind==='author'?(stage?.sim.world||run.world).residents.find(a=>a.kind==='naoto'&&a.id==='naoto'&&a.key==='naoto'):run.party.find(a=>a.kind===row.kind&&a.id===row.id);}
function installDistancePose(sim,actor,view){
 const original=sim.step,heading=view==='front'?Math.PI:0;
 function hold(){actor.x=sim.player.x+85;actor.z=sim.player.z+15;actor.tx=actor.x;actor.tz=actor.z;actor.heading=heading;actor.route=null;actor.behavior='idle';actor.until=1e9;}
 sim.step=function(...args){const events=original.apply(this,args);hold();return events;};hold();
 return ()=>{sim.step=original;};
}
async function run(out){fs.mkdirSync(out,{recursive:true});const filter=process.argv.find(a=>a.startsWith('--keys='))?.slice(7).split(',')||[],rows=captureRows(filter,{includeLegacyStatesDistance:process.argv.includes('--include-legacy-states-distance')}),srv=await serve({nonPlayerFactory:factory}),base='http://127.0.0.1:'+srv.address().port,browser=await require('playwright').chromium.launch({args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']}),errors=[],evidence=[],distance=[];const watch=p=>{p.on('pageerror',e=>errors.push(String(e)));};try{
 const page=await browser.newPage({viewport:{width:320,height:320},deviceScaleFactor:1});watch(page);
 for(const row of rows){const plan=capturePlan(row),prefix=row.kind+'-'+row.id,original=await sharp(path.resolve(__dirname,'../..',row.asset)).trim().resize(280,280,{fit:'contain',background:'#eee9dd'}).extend({top:20,bottom:20,left:20,right:20,background:'#eee9dd'}).png().toBuffer(),views=[{input:original,left:0,top:0}],states=[];
 async function shot(view,emotion,moving,reduced,file){const query=new URLSearchParams({id:plan.modelKey,stage:'0',view,emotion,walk:moving?'1':'0',reduced:reduced?'1':'0'});await page.goto(base+'/character-3d/wave-review.html?'+query);await page.waitForFunction(()=>window.__wave?.ready);const r=await page.evaluate(()=>window.__wave);assert.equal(r.id,plan.modelKey);assert.equal(r.stage,0);assert.equal(r.emotion,emotion);assert.equal(r.moving,moving);assert.equal(r.reduced,reduced);assert.ok(r.triangles>0);await page.screenshot({path:path.join(out,file),type:'jpeg',quality:88});evidence.push({...r,kind:row.kind,masterId:row.id,roleKey:row.key,modelKey:plan.modelKey,reuseFourViews:plan.reuseFourViews,file});}
 for(const[i,v]of plan.fourViews.entries()){const file=prefix+'-0-'+v+'.jpg';await shot(v,'normal',false,false,file);views.push({input:path.join(out,file),left:(i+1)*320,top:0});}
 if(plan.fourViews.length)await sharp({create:{width:1600,height:320,channels:3,background:'#eee9dd'}}).composite(views).jpeg({quality:90}).toFile(path.join(out,prefix+'-views.jpg'));
 for(const[y,em]of SPEC.CANONICAL_EMOTIONS.entries()){states.push({input:original,left:0,top:y*320});for(const[x,p]of [{moving:false,reduced:false},{moving:true,reduced:false},{moving:false,reduced:true},{moving:true,reduced:true}].entries()){const file=prefix+'-0-'+em+'-'+(p.moving?'walk':'idle')+'-'+(p.reduced?'reduced':'normal')+'.jpg';await shot('34',em,p.moving,p.reduced,file);states.push({input:path.join(out,file),left:(x+1)*320,top:y*320});}}
 await sharp({create:{width:1600,height:2560,channels:3,background:'#eee9dd'}}).composite(states).jpeg({quality:90}).toFile(path.join(out,prefix+'-motion.jpg'));
 const ctx=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:2}),pg=await ctx.newPage();watch(pg);await pg.addInitScript({content:'globalThis.__installDistancePose='+installDistancePose.toString()+';globalThis.__stageAuthorResident='+stageAuthorResident.toString()+';globalThis.__distanceActor='+distanceActor.toString()+';'});await pg.addInitScript(s=>localStorage.setItem('naotocchi-save-v1',s),saveFor(row));await pg.goto(base+'/index.html?meguru3d=1&char3d=1&perf=1');await pg.locator('.device.ui-home-active').waitFor({timeout:60000});await pg.locator('#travelBtn').click();await pg.locator('#meguruEnterBtn').waitFor({state:'visible'});await pg.locator('#meguruEnterBtn').click();await pg.locator('#mgrCanvas').waitFor({state:'visible'});try{if(row.kind==='author'){await pg.waitForFunction(()=>globalThis.__meguruRun?.world.residents.some(a=>a.kind==='naoto'&&a.id==='naoto')&&globalThis.__meguruRun.renderer.is3D===false,null,{timeout:60000});await pg.evaluate(()=>{globalThis.__authorStage=globalThis.__stageAuthorResident(globalThis.__meguruRun,globalThis.__meguruBridge,globalThis.installNaotocchiMeguru(globalThis.__meguruBridge));});}await pg.waitForFunction(row=>{const r=globalThis.__meguruRun,a=r&&globalThis.__distanceActor(r,row,globalThis.__authorStage);return a&&r.renderer.char3dPresenter?.has(a);},{kind:row.kind,id:row.id},{timeout:60000});
 for(const view of ['front','back']){const r=await pg.evaluate(async({kind,id,key,modelKey,view})=>{const r=globalThis.__meguruRun,s=globalThis.__authorStage?.sim||r.sim,a=globalThis.__distanceActor(r,{kind,id},globalThis.__authorStage);s.setCameraMotion(false);const spot=s.world.spots.find(x=>x.id==='entry');s.setPlayer(spot.x,spot.z-100);s.camera.yaw=0;if(globalThis.__npRelease)globalThis.__npRelease();globalThis.__npRelease=globalThis.__installDistancePose(s,a,view);if(!s.__npEnv){s.__npEnv=true;const setEnv=s.setEnv.bind(s);s.setEnv=e=>setEnv({...e,time:'day',weather:'sunny'});}s.setEnv(s.env);for(let i=0;i<45;i++)await new Promise(requestAnimationFrame);const SPEC=(await import('/character-3d/spec-esm.mjs')).default;const inst=r.renderer.char3dPresenter.instanceOf(a),target=view==='front'?0:Math.PI,yawError=Math.abs(Math.atan2(Math.sin(inst.holder.rotation.y-target),Math.cos(inst.holder.rotation.y-target)));return {kind,id,key,modelKey,view,actorIdentity:{key:a.key,kind:a.kind,id:a.id,asset:a.asset},authorProvenance:globalThis.__authorStage?.provenance||null,qaPlacement:{region:s.world.regionId,actor:{x:a.x,z:a.z,heading:a.heading},player:{x:s.player.x,z:s.player.z},cameraYaw:s.camera.yaw},actorHeading:a.heading,renderedYaw:inst.holder.rotation.y,yawError,specKey:SPEC.specKeyFor(a),live3d:r.renderer.char3dPresenter.has(a),stats:r.renderer.char3dPresenter.stats()};},{kind:row.kind,id:row.id,key:row.key,modelKey:plan.modelKey,view});assert.ok(r.yawError<.02,'actual rendered heading must match requested '+view);assert.equal(r.specKey.id,plan.modelKey);assert.equal(r.specKey.stage,0);assert.equal(r.specKey.exact,true);assert.ok(r.live3d);assert.equal(r.stats.fallbacks,0);assert.equal(r.stats.failedTemplates,0);const clip=await pg.locator('#mgrCanvas').boundingBox(),file=prefix+'-distance-'+view+'.jpg';await pg.screenshot({path:path.join(out,file),clip,type:'jpeg',quality:92});distance.push({...r,file});}}finally{try{await pg.evaluate(()=>{if(globalThis.__npRelease)globalThis.__npRelease();if(globalThis.__authorStage){globalThis.__authorStage.release();globalThis.__authorStage=null;}});}finally{await ctx.close();}}
 }
 assert.deepEqual(errors,[]);assert.equal(evidence.length,rows.reduce((n,row)=>n+capturePlan(row).fourViews.length+32,0));assert.equal(distance.length,rows.length*2);fs.writeFileSync(path.join(out,'evidence.json'),JSON.stringify({sourceCommit:process.env.GITHUB_SHA||null,platform:'Chromium/SwiftShader; not iPhone',candidateOnly:true,includeLegacyStatesDistance:process.argv.includes('--include-legacy-states-distance'),plans:rows.map(capturePlan),evidence,distance,errors},null,2));
 }finally{await browser.close();srv.close();}}
module.exports={captureRows,capturePlan,saveFor,installDistancePose,stageAuthorResident,distanceActor};if(require.main===module)run(process.argv[2]||'test-results/full-rollout/nonplayer').catch(e=>{console.error(e);process.exitCode=1;});
