"""Typed rows must be generated by the actual resolving source and target."""
import copy,unittest
from test_proxy_population_trigger_latching import case
from test_proxy_population_trigger_effects import case as board_case,resolving
from test_proxy_population_runtime import initial
import proxy_population_challenge_window as connected
import proxy_population_runtime as runtime
import proxy_population_trigger_effects as effects
import proxy_population_trigger_latching as latching
import proxy_continuation_payments as payments
try:import proxy_population_effect_creation as api
except ImportError:api=None


def quick_case(card):
 e,_,_,_=case();c=e['legacy_continuation'];g=c['game_state'];p=g['players']['A'];old=c['activation_zone'][-1]['source_instance_id'];p['discard'].append(old)
 zone,source=next((z,s) for z in ('hand','deck','discard') for s in p[z] if g['cards'][s]['card_id']==card);p[zone].remove(source)
 other=g['players']['B']
 if other['board']['main'] is None:
  main=next(s for s in other['deck'] if g['cards'][s]['card_id'].startswith('M-'));other['deck'].remove(main);other['board']['main']=main
 cap=payments.capability(card);target=None
 if card in payments.STAT_CARDS or card in payments.CONDITIONAL_CARDS:
  owner='A' if card in payments.CONDITIONAL_CARDS or cap.get('target_owner')=='own' else 'B';target=g['players'][owner]['board']['main']
 if cap.get('duration')=='challenge':g['challenge']=dict(challenge_id='challenge-fixture',status='comparing',declaring_actor='A',parameter='power',participants={o:g['players'][o]['board']['main'] for o in 'AB'},started_event_seq=2,result=None)
 link=dict(link_id='response-link-3-'+source,action_type=cap.get('action_type','use_event'),actor='A',source_zone='hand',source_instance_id=source,card_copy_id=g['cards'][source]['card_copy_id'],card_id=card,target_instance_ids=[target] if target else [],candidate_variant='wisdom' if cap.get('choose_parameter') else None,payment=dict(time=cap['base_time_cost']),source_references=[cap['reference']])
 c['activation_zone']=[link];c['response_context'].update(chain_status='resolving',chain_links=[link['link_id']],consecutive_passes=2)
 return e

class CreationTests(unittest.TestCase):
 def setUp(self):self.assertIsNotNone(api,'typed creation audit missing')
 def run_case(self,callback):
  def run(forced):
   with effects.scope():return callback()
  with connected.contract_scope():return runtime.operation(initial(),run)
 def test_actual_quick_typed_creation_binds_source_target_and_exact_row(self):
  def run():
   for card in ('E-fateful-transform','E-big-illness','G-beach-volley','G-baseball-batting','G-air-hockey','G-basketball-3d'):
    e=quick_case(card);r=payments.resolve(e,initial());a=r['new_envelopes'][0];ev=r['new_events'][0];proof=api.audit(e,a,ev)
    self.assertTrue(proof['typed_creation_verified'],(card,proof['errors']));self.assertEqual(proof['created_effect_count'],1)
    family=proof['effect_family'];bad=copy.deepcopy(a);bad['runtime'][family]=[];self.assertTrue(api.audit(e,bad,ev)['errors'])
    bad=copy.deepcopy(a);bad['runtime'][family][-1]['controller']='B';self.assertTrue(api.audit(e,bad,ev)['errors'])
   return {}
  self.run_case(run)
 def test_invalid_target_creates_nothing_and_retains_prior_rows(self):
  def run():
   e=quick_case('G-basketball-3d');g=e['legacy_continuation']['game_state'];p=g['players']['A'];p['discard'].append(p['board']['main']);p['board']['main']=None
   source=next(s for s,v in g['cards'].items() if v['card_id']=='E-fateful-transform');payments.add_modifier(e,'A',source)
   r=payments.resolve(e,initial());a=r['new_envelopes'][0];event=r['new_events'][0];proof=api.audit(e,a,event)
   self.assertEqual(proof['errors'],[]);self.assertEqual(proof['created_effect_count'],0);self.assertTrue(proof['typed_creation_verified'])
   bad=copy.deepcopy(a);bad['runtime']['payment_effects']=[];self.assertTrue(api.audit(e,bad,event)['errors']);return {}
  self.run_case(run)
 def test_positive_board_creation_uses_existing_choice_and_same_source(self):
  def run():
   for card in ('M-antlion-03','P-cliff_goat'):
    e,row=board_case(card);action=latching.current_actions(e,row)[0][0];e,_=effects.activate(e,action,row);e=resolving(e);r=effects.resolve(e,initial());a=r['new_envelopes'][0];ev=r['new_events'][0];proof=api.audit(e,a,ev)
    self.assertEqual(proof['errors'],[],card);self.assertEqual(proof['created_effect_count'],1)
    self.assertFalse(proof['choice_proven']);self.assertFalse(proof['all_rule_opportunities_proven'])
   return {}
  self.run_case(run)
 def test_source_boundary_receipt_and_preserved_rows_mutations_fail(self):
  def run():
   e=quick_case('G-basketball-3d');r=payments.resolve(e,initial());a=r['new_envelopes'][0];event=r['new_events'][0]
   for mode in ('receipt','actor','link','seq','reference','links','action_type'):
    b=copy.deepcopy(e);bad=copy.deepcopy(a);ev=copy.deepcopy(event)
    if mode=='receipt':ev['created_effect']['target_instance_id']='foreign'
    elif mode=='actor':ev['actor']='B'
    elif mode=='link':ev['chain_link_id']='foreign'
    elif mode=='seq':ev['seq']+=1
    elif mode=='reference':ev['source_reference']='foreign'
    elif mode=='links':b['legacy_continuation']['response_context']['chain_links']=[]
    else:b['legacy_continuation']['activation_zone'][-1]['action_type']='activate_board_ability'
    with self.subTest(mode=mode):self.assertTrue(api.audit(b,bad,ev)['errors'])
   return {}
  self.run_case(run)
 def test_challenge_board_stat_sources_and_parameters(self):
  def run():
   for card in ('M-antlion-07','P-anglerfish'):
    e=quick_case('G-baseball-batting');c=e['legacy_continuation'];g=c['game_state'];p=g['players']['A'];p['discard'].append(c['activation_zone'][-1]['source_instance_id'])
    zone,source=next((z,s) for z in ('hand','deck','discard') for s in p[z] if g['cards'][s]['card_id']==card);p[zone].remove(source)
    slot='main' if card.startswith('M-') else 'partner'
    if p['board'][slot]:p['discard'].append(p['board'][slot])
    p['board'][slot]=source
    if slot=='partner':p['board']['partner_stage']=0
    g['challenge']['participants']['A']=p['board']['main'];cap=payments.capability(card)
    link=dict(link_id='response-link-3-'+source,action_type='activate_board_ability',source_zone='board',actor='A',card_id=card,card_copy_id=g['cards'][source]['card_copy_id'],source_instance_id=source,target_instance_ids=[p['board']['main']],candidate_variant='wisdom' if card=='M-antlion-07' else None,payment=dict(time=0),source_references=[cap['reference']])
    c['activation_zone']=[link];c['response_context']['chain_links']=[link['link_id']]
    r=payments.resolve_board_stat(e);a=r['new_envelopes'][0];event=r['new_events'][0];proof=api.audit(e,a,event)
    self.assertEqual(proof['errors'],[],card);self.assertEqual(proof['created_effect_count'],1)
    row=a['runtime']['stat_effects'][-1];self.assertEqual((row['power'],row['wisdom']),(0,2) if card=='M-antlion-07' else (2,0))
   return {}
  self.run_case(run)
 def test_positive_source_or_main_loss_suppresses_creation(self):
  def run():
   for card in ('M-antlion-03','P-cliff_goat'):
    e,row=board_case(card);action=latching.current_actions(e,row)[0][0];e,_=effects.activate(e,action,row);e=resolving(e);p=e['legacy_continuation']['game_state']['players']['A'];p['discard'].append(p['board']['main']);p['board']['main']=None
    r=effects.resolve(e,initial());proof=api.audit(e,r['new_envelopes'][0],r['new_events'][0])
    self.assertEqual(proof['errors'],[],card);self.assertEqual(proof['created_effect_count'],0)
   return {}
  self.run_case(run)
 def test_actual_coverage_rejects_created_row_deletion(self):
  import proxy_population_trigger_coverage as coverage
  def run():
   e=quick_case('E-fateful-transform');r=payments.resolve(e,initial());a=copy.deepcopy(r['new_envelopes'][0]);a['runtime']['payment_effects']=[]
   step=dict(source_envelope=e,events=r['new_events'],envelopes=[a])
   with self.assertRaisesRegex(ValueError,'typed effect creation'):coverage.audit(dict(source_envelope=e,steps=[step]),[],dict(occurrences=[]))
   return {}
  self.run_case(run)
 def test_creation_on_unrelated_transition_is_rejected(self):
  def run():
   e=quick_case('E-fateful-transform');r=payments.resolve(e,initial());ev=dict(r['new_events'][0],action_type='response_pass')
   self.assertTrue(api.audit(e,r['new_envelopes'][0],ev)['errors']);return {}
  self.run_case(run)

if __name__=='__main__':unittest.main()
