"""Derive conservative geometry from existing PNGs; never modify the artwork.
Run with Python + Pillow after an approved asset update.
"""
import json
from pathlib import Path
from PIL import Image

root = Path(__file__).resolve().parents[1]
def hull(points):
    pts = sorted(set(points))
    def cross(o, a, b):
        return (a[0]-o[0])*(b[1]-o[1])-(a[1]-o[1])*(b[0]-o[0])
    lower, upper = [], []
    for sequence, output in ((pts, lower), (reversed(pts), upper)):
        for p in sequence:
            while len(output) >= 2 and cross(output[-2], output[-1], p) <= 0:
                output.pop()
            output.append(p)
    return lower[:-1] + upper[:-1]

data = {}
for path in sorted((root/'assets/characters').rglob('*.png')):
    with Image.open(path) as img:
        alpha = img.convert('RGBA').getchannel('A')
        bbox = alpha.getbbox()
        if not bbox:
            continue
        w, h = img.size
        points = []
        for y in range(h):
            xs = [x for x in range(w) if alpha.getpixel((x,y)) > 0]
            if xs:
                for x in (min(xs), max(xs)+1):
                    points.extend([(x,y),(x,y+1)])
        normalized = [[round(x/w*128,4),round(y/h*128,4)] for x,y in hull(points)]
        data[str(path.relative_to(root))] = {'box':[bbox[0]/w*128,bbox[1]/h*128,bbox[2]/w*128,bbox[3]/h*128], 'hull':normalized}
out = '// Generated by tools/generate-cast-bounds.py from unmodified PNG alpha.\n'
out += '(function(root){ const bounds = '+json.dumps(data,ensure_ascii=False,separators=(',',':'))+';\n'
out += "if(typeof module==='object' && module.exports) module.exports=bounds; else root.NaotocchiCastBounds=bounds;\n})(typeof window!=='undefined'?window:globalThis);\n"
(root/'cast-bounds.js').write_text(out)
print(f'Geometry for {len(data)} images; source images unchanged')
